# Site
name: "ppamppamman"
title: "ppamppamman"
description: "빰빰맨입니다"
logo: 'assets/images/profile_character.png'
favicon: 'assets/images/profile_character.png'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'ppamppamman.github.io'
include: ["_pages"]
permalink: /:title/
email: ppamppamman@gmail.com

# Authors
authors:
  ppamppamman:
    name: ppamppamman
    display_name: ppamppamman
    gravatar: efb77effe811ca1731465b399b6dda9c
    email: ppamppamman@gmail.com
    web: http://resume.ppamppam.me/
    description: "가끔 카카오티비에서 고전게임 방송을 하는 개발자 빰빰맨입니다."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
# highlighter: rouge
# kramdown:
#   # syntax_highlighter_opts:
#   #   disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
